/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElDatePicker: typeof import('element-plus/es').ElDatePicker
  const ElSelec: typeof import('element-plus/es').ElSelec
}
